### ISSUE TITLE
yarn workspaces fails when using yarn 3

### ISSUE THREAD

**Issue by rockerBOO** [sourcegraph/scip-typescript#163]
Yarn changed some of the API and this causes the workspaces list to fail. 

```
Using Docker executor with image sourcegraph/scip-typescript:latest ...
Pulling docker image sourcegraph/scip-typescript:latest ...
Using docker image sha256:44e395dba134f5a6ef383dffe158f4ee2a3b184b470b1be1b585e039de3ae7f2 for sourcegraph/scip-typescript:latest with digest sourcegraph/scip-typescript@sha256:0d0b600a1ae3b4bcec3966c2e95f6064a77ff0c8afbc26a7fe77962467dbe1e2 ...
Preparing environment
Running on runner--project-0-concurrent-0 via Monolith...
Getting source from Git repository
Fetching changes...
Initialized empty Git repository in /builds/project-0/.git/
Created fresh repository.
Checking out 0cf55661 as master...

Skipping Git submodules setup
Executing "step_script" stage of the job script
Using docker image sha256:44e395dba134f5a6ef383dffe158f4ee2a3b184b470b1be1b585e039de3ae7f2 for sourcegraph/scip-typescript:latest with digest sourcegraph/scip-typescript@sha256:0d0b600a1ae3b4bcec3966c2e95f6064a77ff0c8afbc26a7fe77962467dbe1e2 ...
$ scip-typescript index --yarn-workspaces
node:child_process:891
    throw err;
    ^

Error: Command failed: yarn --silent --json workspaces info
    at checkExecSyncError (node:child_process:817:11)
    at Object.execSync (node:child_process:888:15)
    at listYarnWorkspaces (/usr/local/share/.config/yarn/global/node_modules/@sourcegraph/scip-typescript/dist/src/main.js:207:30)
    at indexCommand (/usr/local/share/.config/yarn/global/node_modules/@sourcegraph/scip-typescript/dist/src/main.js:49:26)
    at /usr/local/share/.config/yarn/global/node_modules/@sourcegraph/scip-typescript/dist/src/main.js:43:66
    at Command.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/@sourcegraph/scip-typescript/dist/src/CommandLineOptions.js:24:9)
    at Command.listener [as _actionHandler] (/usr/local/share/.config/yarn/global/node_modules/commander/lib/command.js:482:17)
    at /usr/local/share/.config/yarn/global/node_modules/commander/lib/command.js:1239:65
    at Command._chainOrCall (/usr/local/share/.config/yarn/global/node_modules/commander/lib/command.js:1154:12) {
  status: 1,
  signal: null,
  output: [
    null,
    'Unknown Syntax Error: Command not found; did you mean one of:\n' +
      '\n' +
      '  0. yarn cache clean [--mirror] [--all]\n' +
      '  1. yarn cache clean [--mirror] [--all]\n' +
      '  2. yarn config get [--json] [--no-redacted] <name>\n' +
      '  3. yarn config set [--json] [-H,--home] <name> <value>\n' +
      '  4. yarn config unset [-H,--home] <name>\n' +
      '  5. yarn set resolution [-s,--save] <descriptor> <resolution>\n' +
      '  6. yarn set version from sources [--path #0] [--repository #0] [--branch #0] [--plugin #0] [--no-minify] [-f,--force] [--skip-plugins]\n' +
      '  7. yarn set version [--only-if-needed] <version>\n' +
      '  8. yarn workspaces list [--since] [-R,--recursive] [-v,--verbose] [--json]\n' +
      ...
```
Or more simply:

```
➜ yarn --silent --json workspaces info
Unknown Syntax Error: Command not found; did you mean one of:
```

```
yarn --version
3.1.1
```

Using `yarn workspaces list --json` you could get each location per line.

```
yarn workspaces list --json
{"location":".","name":null}
{"location":"create","name":"create"}
{"location":"site","name":"site"}
```

**Comment by olafurpg** [comment]
Thank you for reporting! We just released v0.2.9, which adds a new `--yarn-berry-workspaces` flag that should be compatible with the Yarn v3 API. Please let us know if you have any issues using that flag :)
